services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config", "/etc/otel-collector-config.yaml"]

  portkey-gateway:
    image: portkeyai/gateway:latest
    container_name: portkey-gateway
    ports:
      - "8787:8787"

    environment:
      - OTEL_PUSH_ENABLED=true
      - OTEL_ENDPOINT=http://otel-collector:4317

      # — Your Portkey credentials —
      - PORTKEY_API_KEY=${PORTKEY_API_KEY}
      - PORTKEY_VIRTUAL_KEY=${PORTKEY_VIRTUAL_KEY}

    restart: unless-stopped
