# LiteLLM Configuration with Wildcard Pass-through for Claude Code
# This allows Claude Code to select any model while maintaining observability

model_list:
  # All available Claude models from Anthropic API
  # Claude Opus 4.1 (Latest)
  - model_name: "claude-opus-4-1-20250805"
    litellm_params:
      model: "anthropic/claude-opus-4-1-20250805"
      api_key: os.environ/ANTHROPIC_API_KEY

  # Claude Opus 4
  - model_name: "claude-opus-4-20250514"
    litellm_params:
      model: "anthropic/claude-opus-4-20250514"
      api_key: os.environ/ANTHROPIC_API_KEY

  # Claude Sonnet 4 (Current Claude Code default)
  - model_name: "claude-sonnet-4-20250514"
    litellm_params:
      model: "anthropic/claude-sonnet-4-20250514"
      api_key: os.environ/ANTHROPIC_API_KEY

  # Claude Sonnet 3.7
  - model_name: "claude-3-7-sonnet-20250219"
    litellm_params:
      model: "anthropic/claude-3-7-sonnet-20250219"
      api_key: os.environ/ANTHROPIC_API_KEY

  # Claude Sonnet 3.5 (New)
  - model_name: "claude-3-5-sonnet-20241022"
    litellm_params:
      model: "anthropic/claude-3-5-sonnet-20241022"
      api_key: os.environ/ANTHROPIC_API_KEY

  # Claude Haiku 3.5
  - model_name: "claude-3-5-haiku-20241022"
    litellm_params:
      model: "anthropic/claude-3-5-haiku-20241022" 
      api_key: os.environ/ANTHROPIC_API_KEY

  # Claude Sonnet 3.5 (Old)
  - model_name: "claude-3-5-sonnet-20240620"
    litellm_params:
      model: "anthropic/claude-3-5-sonnet-20240620"
      api_key: os.environ/ANTHROPIC_API_KEY

  # Claude Haiku 3
  - model_name: "claude-3-haiku-20240307"
    litellm_params:
      model: "anthropic/claude-3-haiku-20240307"
      api_key: os.environ/ANTHROPIC_API_KEY


litellm_settings:
  # Enable Arize callbacks for observability (when ARIZE_API_KEY is set)
  callbacks: ["arize"]
  
  # Don't drop any parameters - preserve everything Claude Code sends
  drop_params: false
  
  # Enable verbose logging to see what models Claude Code selects
  set_verbose: true
  
  # Allow pass-through of all parameters
  pass_through_params: true
  
  # Disable authentication by default (can be overridden with LITELLM_MASTER_KEY)
  disable_auth: true

# Router settings for flexible routing
router_settings:
  routing_strategy: "simple-shuffle"
  # Don't enforce model restrictions
  enable_pre_call_checks: false
  # Disable all health checks that might block models
  disable_cooldowns: true
  allowed_fails: 1000

# Arize environment configuration
environment:
  - ARIZE_API_KEY=${ARIZE_API_KEY}
  - ARIZE_SPACE_KEY=${ARIZE_SPACE_KEY}
  - ARIZE_ENDPOINT=https://otlp.arize.com/v1