model_list:
  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: anthropic/claude-opus-4-1-20250805
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

  # Map Claude Code's expected models to Anthropic
  - model_name: claude-opus-4-20250514
    litellm_params:
      model: anthropic/claude-opus-4-20250514
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

  - model_name: claude-3-sonnet-20240229
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

  # Map the generic names Claude Code might use
  - model_name: sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

  - model_name: haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/CLAUDE_OAUTH_ACCESS_TOKEN

litellm_settings:
  callbacks: ["arize"]
  drop_params: false # Don't drop any parameters
  set_verbose: true # Enable verbose logging to debug API calls

environment:
  - ARIZE_API_KEY=${ARIZE_API_KEY}
  - ARIZE_SPACE_KEY=${ARIZE_SPACE_KEY} # LiteLLM still reads this name
  - ARIZE_ENDPOINT=https://otlp.arize.com/v1
