#!/usr/bin/env python3
"""Render docs/query-cookbook-store.md from the oracle's recipes, so the cookbook for the
new store is the set of questions the oracle proves against Phoenix every morning, and
cannot drift from it. Re-run after changing scripts/migration_oracle.py.

    uv run python scripts/render_store_cookbook.py
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from migration_oracle import BIND, STORE  # noqa: E402

TITLES = {
    "count": "How many spans and traces do we hold?",
    "daily": "Spans per day",
    "status": "How many calls errored?",
    "names": "What kinds of spans are there?",
    "tokens_daily": "Tokens per day",
    "cache_daily": "Prompt cache read and write per day",
    "by_model": "Which models, how much?",
    "thinking": "Is extended thinking on?",
    "roster": "Who is active? (per-trace identity)",
    "sessions": "How many sessions?",
    "errors": "The errored spans",
    "trace_shape": "The biggest traces, as parent and child",
    "tools": "What tools did the agent run?",
    "sample_content": "A deterministic content sample (the oracle's diff sample)",
    "autonomy": "Autonomy ratio: agent-continued turns versus text turns",
}

HEAD = """# Query cookbook for the span store

Every recipe here is one the migration oracle runs against Phoenix and the store daily, and
they agree on 75 of 75 across five projects (2026-09-11). The SQL is the typed layout's; a
`source` filter scopes one project so two never blend. Run any of them with

```bash
dal store query "<sql>"                       # configured store, typed layout
dal store query --format json "<sql>"         # for an agent to read
```

Generated by `scripts/render_store_cookbook.py` from `scripts/migration_oracle.py`. Edit the
oracle, not this file.

"""


# Per-harness recipes (ENG2-402). Kept here, not in the oracle: there is no old-store
# equivalent to diff them against. Split across lines only to fit the line limit; the
# rendered doc shows each on one line, like the recipes above.
HARNESS_QUERIES = {
    "HARNESS_Q1": (
        "SELECT COALESCE(agent, 'claude-code (proxy)') AS harness, count(*) "
        "FILTER (WHERE span_kind = 'LLM')::BIGINT AS llm_calls, "
        "sum(tokens_prompt)::BIGINT AS prompt, sum(tokens_cache_read)::BIGINT "
        "AS cache_read, sum(tokens_completion)::BIGINT AS completion FROM spans "
        "GROUP BY 1 ORDER BY 2 DESC"
    ),
    "HARNESS_Q2": (
        "SELECT COALESCE(agent, 'claude-code (proxy)') AS harness, tool_kind, "
        "count(*)::BIGINT AS n FROM spans WHERE tool_kind IS NOT NULL GROUP BY "
        "1, 2 ORDER BY 1, 3 DESC"
    ),
    "HARNESS_Q3": (
        "SELECT ticket, COALESCE(agent, 'claude-code (proxy)') AS harness, "
        "count(DISTINCT trace_id)::BIGINT AS traces, "
        "sum(COALESCE(tokens_prompt, 0) + COALESCE(tokens_completion, "
        "0))::BIGINT AS tokens FROM spans WHERE ticket IS NOT NULL GROUP BY 1, "
        "2 ORDER BY 4 DESC LIMIT 20"
    ),
}


def main() -> int:
    out = [HEAD]
    for i, (name, sql) in enumerate(STORE.items(), 1):
        body = (
            sql.format(**BIND["typed"]).replace("FROM sp", "FROM spans").replace(" sp ", " spans ")
        )
        out.append(f"## {i}. {TITLES.get(name, name)}\n\n```sql\n{body}\n```\n")
    out.append(
        """## Scoping to one project

Every query above takes `WHERE source = '<name>'` on `spans`; `dal store status` lists the
sources present. The dead `dev-agent-lens` project is 93 percent of May and flips the
autonomy headline when blended with `sf-workspaces`; scope it out or in on purpose.

## Bringing your own Claude folder

```bash
dal ingest-sessions --include '*your-repo*' --project my-claude --to-store --yes
dal store layout typed && dal store verify --from-parquet '<store>/spans_raw/**/*.parquet'
```

Twelve seconds for three weeks of sessions on a laptop. Then any recipe above, scoped to
`source = 'my-claude'`.

## Splitting by harness (Claude Code, Codex)

`agent` names the harness that wrote a session: `claude-code` or `codex` for sessions loaded
from files, NULL for proxy traffic (which is Claude Code today). `tool_kind` puts every
harness's tools in one vocabulary (`shell`, `edit`, `read`, `search`, `plan`, `mcp`, ...), so
`Bash` and Codex's `exec_command` count as the same thing. Load Codex sessions with:

```bash
dal ingest-sessions --agent codex --include '*your-repo*' --project my-codex --to-store --yes
```

Tokens and cache by harness:

```sql
{HARNESS_Q1}
```

What each harness spends its tool calls on:

```sql
{HARNESS_Q2}
```

Tokens per ticket, per harness:

```sql
{HARNESS_Q3}
```
""".format(**HARNESS_QUERIES)
    )
    path = os.path.join(os.path.dirname(__file__), "..", "docs", "query-cookbook-store.md")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(path)}: {len(STORE)} recipes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
