"""
Token Breakdown Analysis Module

Provides detailed token counting by message type:
- Input tokens: tool calls, user messages, system prompts
- Output tokens: model-generated responses

This distinction is critical for cost calculation since input and output
tokens have different pricing tiers.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

from dev_agent_lens.analysis.classify import SpanCategory, classify_span


@dataclass
class TokenBreakdown:
    """
    Detailed breakdown of tokens by message type.

    Input categories:
        - tool_tokens: Tokens from tool calls/responses
        - user_tokens: Tokens from user messages
        - system_tokens: Tokens from system prompts

    Output categories:
        - model_tokens: Tokens generated by the model
    """

    # Input token breakdown
    tool_tokens: int = 0
    user_tokens: int = 0
    system_tokens: int = 0

    # Output tokens
    model_tokens: int = 0

    # Raw totals from span metadata
    raw_input_tokens: int = 0
    raw_output_tokens: int = 0
    raw_total_tokens: int = 0

    # Span counts by type
    tool_spans: int = 0
    llm_spans: int = 0
    internal_spans: int = 0

    @property
    def total_input_tokens(self) -> int:
        """Total input tokens (all categories)."""
        return self.tool_tokens + self.user_tokens + self.system_tokens

    @property
    def total_output_tokens(self) -> int:
        """Total output tokens (model-generated)."""
        return self.model_tokens

    @property
    def total_tokens(self) -> int:
        """Total tokens across all categories."""
        return self.total_input_tokens + self.total_output_tokens

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "input_breakdown": {
                "tool_tokens": self.tool_tokens,
                "user_tokens": self.user_tokens,
                "system_tokens": self.system_tokens,
                "total_input": self.total_input_tokens,
            },
            "output_breakdown": {
                "model_tokens": self.model_tokens,
                "total_output": self.total_output_tokens,
            },
            "totals": {
                "total_tokens": self.total_tokens,
                "raw_input_tokens": self.raw_input_tokens,
                "raw_output_tokens": self.raw_output_tokens,
                "raw_total_tokens": self.raw_total_tokens,
            },
            "span_counts": {
                "tool_spans": self.tool_spans,
                "llm_spans": self.llm_spans,
                "internal_spans": self.internal_spans,
            },
        }


def _safe_int(value: Any) -> int:
    """Safely convert a value to int, handling NaN and None."""
    if value is None:
        return 0
    try:
        float_val = float(value)
        if math.isnan(float_val):
            return 0
        return int(float_val)
    except (ValueError, TypeError):
        return 0


def _get_message_role(message: dict[str, Any]) -> str:
    """Extract role from a message dict."""
    # Try various message formats
    role = message.get("message.role") or message.get("role", "")
    return str(role).lower()


def _estimate_tokens_from_content(content: str, chars_per_token: float = 4.0) -> int:
    """
    Estimate token count from content length.

    Uses a simple heuristic: ~4 characters per token for English text.
    This is a fallback when actual token counts aren't available.
    """
    if not content:
        return 0
    return int(len(content) / chars_per_token)


def analyze_span_tokens(span: dict[str, Any]) -> TokenBreakdown:
    """
    Analyze token breakdown for a single span.

    Classifies tokens based on span type and message content:
    - Tool spans: tokens attributed to tool calls
    - LLM spans with user messages: attributed to user
    - System messages: attributed to system
    - Model output: attributed to model

    Args:
        span: A span dictionary with token counts and messages

    Returns:
        TokenBreakdown with categorized tokens
    """
    breakdown = TokenBreakdown()

    # Get raw token counts
    raw_input = _safe_int(span.get("llm_token_count_prompt"))
    raw_output = _safe_int(span.get("llm_token_count_completion"))
    raw_total = _safe_int(span.get("llm_token_count_total"))

    breakdown.raw_input_tokens = raw_input
    breakdown.raw_output_tokens = raw_output
    breakdown.raw_total_tokens = raw_total if raw_total > 0 else raw_input + raw_output

    # Classify the span
    classification = classify_span(span)

    # Categorize based on span type
    if classification.category == SpanCategory.TOOLS:
        # Tool span - all tokens are tool-related
        breakdown.tool_tokens = raw_input + raw_output
        breakdown.tool_spans = 1

    elif classification.category in (SpanCategory.MAIN, SpanCategory.HAIKU_HOLDOVER):
        # LLM span - break down by message roles
        breakdown.llm_spans = 1

        # Try to get input messages for detailed breakdown
        input_messages = span.get("llm_input_messages") or span.get("attributes.llm.input_messages") or []

        if isinstance(input_messages, list) and input_messages:
            # Count tokens by role
            system_chars = 0
            user_chars = 0
            assistant_chars = 0
            tool_chars = 0

            for msg in input_messages:
                if not isinstance(msg, dict):
                    continue

                role = _get_message_role(msg)
                content = str(msg.get("message.content") or msg.get("content") or "")
                content_len = len(content)

                if role == "system":
                    system_chars += content_len
                elif role == "user":
                    user_chars += content_len
                elif role == "assistant":
                    # Previous assistant responses in context
                    assistant_chars += content_len
                elif role in ("tool", "function"):
                    tool_chars += content_len
                else:
                    # Unknown role - attribute to user
                    user_chars += content_len

            # Calculate proportions
            total_chars = system_chars + user_chars + assistant_chars + tool_chars

            if total_chars > 0 and raw_input > 0:
                # Distribute input tokens proportionally
                breakdown.system_tokens = int(raw_input * system_chars / total_chars)
                breakdown.user_tokens = int(raw_input * (user_chars + assistant_chars) / total_chars)
                breakdown.tool_tokens = int(raw_input * tool_chars / total_chars)

                # Ensure we account for all tokens (rounding adjustment)
                allocated = breakdown.system_tokens + breakdown.user_tokens + breakdown.tool_tokens
                if allocated < raw_input:
                    breakdown.user_tokens += raw_input - allocated
            else:
                # No message breakdown available - attribute all to user
                breakdown.user_tokens = raw_input
        else:
            # No messages - use input value to guess
            input_value = span.get("input_value") or ""
            if "system" in str(input_value).lower()[:500]:
                breakdown.system_tokens = raw_input
            else:
                breakdown.user_tokens = raw_input

        # Output tokens are model-generated
        breakdown.model_tokens = raw_output

    elif classification.category == SpanCategory.INTERNAL:
        # Internal span - usually system processing
        breakdown.system_tokens = raw_input
        breakdown.model_tokens = raw_output
        breakdown.internal_spans = 1

    else:
        # Unknown - attribute to user/model
        breakdown.user_tokens = raw_input
        breakdown.model_tokens = raw_output

    return breakdown


def analyze_session_tokens(spans: list[dict[str, Any]]) -> TokenBreakdown:
    """
    Analyze token breakdown for an entire session.

    Aggregates token counts from all spans in the session.

    Args:
        spans: List of span dictionaries

    Returns:
        TokenBreakdown with aggregated token counts
    """
    total = TokenBreakdown()

    for span in spans:
        span_breakdown = analyze_span_tokens(span)

        # Aggregate counts
        total.tool_tokens += span_breakdown.tool_tokens
        total.user_tokens += span_breakdown.user_tokens
        total.system_tokens += span_breakdown.system_tokens
        total.model_tokens += span_breakdown.model_tokens

        total.raw_input_tokens += span_breakdown.raw_input_tokens
        total.raw_output_tokens += span_breakdown.raw_output_tokens
        total.raw_total_tokens += span_breakdown.raw_total_tokens

        total.tool_spans += span_breakdown.tool_spans
        total.llm_spans += span_breakdown.llm_spans
        total.internal_spans += span_breakdown.internal_spans

    return total


def estimate_cost(
    breakdown: TokenBreakdown,
    input_cost_per_million: float = 3.0,
    output_cost_per_million: float = 15.0,
) -> dict[str, float]:
    """
    Estimate cost from token breakdown.

    Default pricing is Claude Sonnet rates:
    - Input: $3 per million tokens
    - Output: $15 per million tokens

    Args:
        breakdown: Token breakdown to price
        input_cost_per_million: Cost per million input tokens
        output_cost_per_million: Cost per million output tokens

    Returns:
        Dictionary with cost breakdown
    """
    input_tokens = breakdown.total_input_tokens
    output_tokens = breakdown.total_output_tokens

    input_cost = (input_tokens / 1_000_000) * input_cost_per_million
    output_cost = (output_tokens / 1_000_000) * output_cost_per_million
    total_cost = input_cost + output_cost

    return {
        "input_cost_usd": round(input_cost, 6),
        "output_cost_usd": round(output_cost, 6),
        "total_cost_usd": round(total_cost, 6),
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "input_cost_per_million": input_cost_per_million,
        "output_cost_per_million": output_cost_per_million,
    }
